"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.regExForFirstLine = exports.regExAddedCodeSection = void 0;
const commentOpen = '(\\/\\/|{\\/\\*)';
const endOfFirstLine = '( \\*\\/\\}\\n|\\n)';
const locationSpec = '(\\w*), comp: (\\w*), loc: (\\w*)';
const content = '((.|\n)*?)';
const firstLineBody = `${commentOpen} np__added_start unit: ${locationSpec}${endOfFirstLine}`;
const fullRegExBody = `${firstLineBody}${content}${commentOpen} np__added_end`;
exports.regExAddedCodeSection = new RegExp(fullRegExBody, 'g');
exports.regExForFirstLine = new RegExp(firstLineBody, 'g');
