mutation CREATE_STACK(
	$name: String
	$licenseId: String
	$modName: String
	$modEmail: String
	$modPassword: String
) {
	stack: CreateStack(
		name: $name
		licenseId: $licenseId
    modName: $modName
    modEmail: $modEmail
    modPassword: $modPassword
	) {
		  id,
      name,
      clientId,
      moderators { id }
  }
}
