mutation EXECUTE_ACTION($actionId: ID!, $executionParameters: String, $unrestricted: Boolean) {
  ExecuteAction(actionId: $actionId, executionParameters: $executionParameters, unrestricted: $unrestricted)
}
