mutation REGISTER_USER(
  $userClassId: ID!
  $name: String!
  $firstName: String!
  $lastName: String!
  $email: String!
  $password: String!
  $formValues: String
  )
 {
      user: CreateUserOnPlatform(
        userClass: $userClassId
        name: $name
        firstName: $firstName
        lastName: $lastName
        email: $email
        password: $password
        formValues: $formValues
      )
    {
      id
      name
      __typename
    }
}
