query UNIT($id: ID!, $typeRelationships: String!, $parameters: String) { unitData(unitId: $id, typeRelationships: $typeRelationships, parameters: $parameters) { instance { ...TaskParts __typename } children { typeId instances { instance { ...TaskChildParts __typename } __typename } __typename } __typename } } fragment TaskParts on Instance { id value __typename } fragment TaskChildParts on Instance { id value __typename }
