mutation resetForgottenPassword(
    $userNameOrEmail: String
    $stackId: ID
    $code: String
    $password: String
) {
  ResetForgottenPassword(
      userNameOrEmail:$userNameOrEmail
      stackId:$stackId
      code:$code
      password:$password
  )
}
