query unitData($id: ID!, $typeRelationships:String!, $parameters: String!, $unrestricted: Boolean!) {
  unitData(unitId: $id, typeRelationships:$typeRelationships, parameters: $parameters, unrestricted: $unrestricted){
    instance {
        id,
        value,
        order
    },
    children {
        typeId,
        instances {
            instance {
                id,
                value,
                order
            },
            children {
                typeId,
                instances {
                    instance {
                        id,
                        value,
                        order
                    },
                    children {
                        typeId,
                        instances {
                            instance {
                                id,
                                value,
                                order
                            },
                            children {
                                typeId,
                                instances {
                                    instance {
                                        id,
                                        value,
                                        order
                                    },

                                }
                            }

                        }
                    }
                }
            }
        }
    }
}}

